### ISSUE TITLE
Support oneorzero rule?

### ISSUE THREAD

**Issue by levey** [mattt/TTTLocalizedPluralString#31]
0 and 1 in english is most same, so will this rule be convenient?

**Comment by mattt** [comment]
There is no such thing as a "oneorzero" rule. English has a "one" rule and an "other" for everything else. See [Unicode Language Plural Rules ](http://unicode.org/repos/cldr-tmp/trunk/diff/supplemental/language_plural_rules.html)

**Comment by levey** [comment]
Thank you very much Matttttt!
