### ISSUE TITLE
key trouble

### ISSUE THREAD

**Issue by kampfgnu** [mattt/TTTLocalizedPluralString#33]
hi,

why does 
```
TTTLocalizedPluralStringKeyForCountAndSingularNounForLanguage
```

return a string with format 
```
@"%%d %@ (plural rule: %@)" 
```
this adds a %d to every key and will then not be found

e.g. i have a key-value pair in my Localizable.strings:
```
"tour.stop (plural rule: one)" = "%i Stop";
"tour.stop (plural rule: other)" = "%i Stops";
```

using "tour.stop" as the key with count=1 will create this new key: "%d tour.stop (plural rule: one)".
this key does not exist, so it will fail.

**Comment by mattt** [comment]
Because that's the format the keys are looking for.

Your keys should be:

```
"%d tour.stop (plural rule: one)" = "%i Stop";
"%d tour.stop (plural rule: other)" = "%i Stops";
```

**Comment by kampfgnu** [comment]
yeah thanks, i misunderstood the intend of your code, sorry for bothering you ;)
